// Disposable local fixture. No production accounts, inboxes or credentials.
import assert from "node:assert/strict";
import { buildServer } from "../../src/api/server.js";
import { MemoryStore } from "../../src/store/memoryStore.js";
import fastifyStatic from "@fastify/static";
import { resolve } from "node:path";
if (process.env.NODE_ENV === "production") throw Error("Local fixture only");
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || "playwright");
const store = new MemoryStore();
const app = await buildServer(store);
await app.register(fastifyStatic, { root: resolve("web/dist") });
const session = await store.createSessionForUser("usr_daniel");
store.users.get("usr_daniel")!.totpEnabled = true;
store.passkeyCredentials.set("fixture", { id: "fixture", userId: "usr_daniel", credentialId: "fixture", publicKey: Buffer.from("fixture"), counter: 0, transports: [], friendlyName: "Fixture" });
await app.listen({ host: "127.0.0.1", port: 4191 });
const browser = await chromium.launch({ channel: "chrome", headless: true });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  await context.addCookies([{ name: "pobox_watch_session", value: session.id, url: "http://127.0.0.1:4191" }]);
  const page = await context.newPage();
  page.setDefaultTimeout(10000);
  await page.route("**/api/v1/auth/login", (route: any) => route.fulfill({ json: { ok: true } }));
  await page.goto("http://127.0.0.1:4191");
  await page.getByRole("button", { name: "Use Password to Set Up Security" }).click();
  await page.getByLabel("Email", { exact: true }).fill("daniel@example.com");
  await page.getByLabel("Password", { exact: true }).fill("fixture");
  await page.getByRole("button", { name: "Continue with Password" }).click();
  await page.getByRole("button", { name: "Got It" }).click();
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  await page.getByLabel("Current password", { exact: true }).fill("wrong");
  await page.getByLabel("New password", { exact: true }).fill("NewPassword12345!");
  await page.getByLabel("Confirm new password", { exact: true }).fill("NewPassword12345!");
  await page.getByRole("button", { name: "Update Password" }).click();
  await page.getByText("Current password is incorrect.", { exact: true }).waitFor();
  await page.getByLabel("Current password", { exact: true }).fill("Password123!");
  await page.screenshot({ path: "/tmp/pobox-password-settings.png", fullPage: true });
  await page.getByRole("button", { name: "Update Password" }).click();
  await page.getByText(/Password updated/).waitFor();
  assert.equal(store.sessions.has(session.id), false);
  const token = (await store.requestPasswordReset("john@example.com"))!;
  await page.goto(`http://127.0.0.1:4191/#reset-password=${token}`);
  await page.getByLabel("New password", { exact: true }).fill("JohnPassword12345!");
  await page.getByLabel("Confirm new password", { exact: true }).fill("JohnPassword12345!");
  await page.getByRole("button", { name: "Update Password" }).click();
  await page.getByText(/Password updated/).waitFor();
  assert.equal(new URL(page.url()).hash, "");
  await assert.rejects(store.resetPassword(token, "AnotherPassword123!"));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("http://127.0.0.1:4191/?forgot-password=1");
  await page.getByLabel("Email", { exact: true }).fill("john@example.com");
  await page.getByRole("button", { name: "Send Reset Link" }).click();
  await page.getByText(/email is not configured/).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: "/tmp/pobox-password-forgot-mobile.png", fullPage: true });
  console.log("PASS password change, reset, session revocation, token reuse, missing SMTP and mobile layout");
} finally { await browser.close(); await app.close(); }
